#  Systems of Linear Equations

<p>Example 1.1 <p/>
Below are the row operations following textbook's order of operations to solve Eqn (3)

In [1]:
import numpy as np
import sympy 

dim=3

def Replace(target_row,other_row,scale):
    Id=np.eye(dim)
    out=np.matrix(Id)
    out[target_row,:]=Id[target_row,:]+scale*Id[other_row,:]
    return out

def Interchange(row1,row2):
    Id=np.eye(dim)
    out=np.matrix(Id)
    out[row1,:]=Id[row2,:]
    out[row2,:]=Id[row1,:]
    return out
    
def Scale(row,alpha):
    Id=np.eye(dim)
    out=np.matrix(Id)
    out[row,:]=alpha*Id[row,:]
    return out
    

Example 1.1 in matrix notation

In [2]:
A=np.array([[1,-2,1,0],[0,2,-8,8],[5,0,-5,10]])
print(A)

[[ 1 -2  1  0]
 [ 0  2 -8  8]
 [ 5  0 -5 10]]


<p>Python begins index count at 0, which is of critical importance for matrix indices</p>

Step 1: Replace-5*A[0,] to A[2,] , meaning 'Add -5 times eqn 1 to eqn 3'

In [3]:
A1=np.dot(Replace(2,0,-5),A)
print(A1)

[[  1.  -2.   1.   0.]
 [  0.   2.  -8.   8.]
 [  0.  10. -10.  10.]]


Step 2: Scale A[1,] by 1/2, meaning 'Multiply eqn 2 by 1/2'

In [4]:
A2=np.dot(Scale(1,.5),A1)
print(A2)

[[  1.  -2.   1.   0.]
 [  0.   1.  -4.   4.]
 [  0.  10. -10.  10.]]


Step 3: Replace -10*A[1,] to A[2,] , meaning 'Adds -10 times eqn 2 to eqn 3'

In [5]:
A3=np.dot(Replace(2,1,-10),A2)
print(A3)

[[  1.  -2.   1.   0.]
 [  0.   1.  -4.   4.]
 [  0.   0.  30. -30.]]


Step 4: Scale A[2,] by 1/30

In [6]:
A4=np.dot(Scale(2,1/30.),A3)
print(A4)

[[ 1. -2.  1.  0.]
 [ 0.  1. -4.  4.]
 [ 0.  0.  1. -1.]]


Step 5: Replace 4*A[2,] to A[1,] and Step 6: Replace -1*A[2,] to A[0,]

In [7]:
A5=np.dot(Replace(1,2,4),A4)
A6=np.dot(Replace(0,2,-1),A5)
print(A6)

[[ 1. -2.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1. -1.]]


Step 7: Replace 2*A[1,] to A[0,]

In [8]:
A7=np.dot(Replace(0,1,2),A6)
print(A7)

[[ 1.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1. -1.]]


<p> The above tedious step-wise operations is to show the elementary row operations. </p>
<p>The form of the solution is called row reduced echelon form (rref).</p>
Python has a function to solve for rref.

The Python function numpy.linalg can solve system of linear eqns

In [10]:
A = np.array([[1,-2,1],[0,2,-8],[5,0,-5]])
B = np.array([0,8,10])
x=np.linalg.solve(A,B)
print(x)

[ 1.  0. -1.]
